package com.wellcome.main.dto.api.paths

object QueryString {
    const val LOCALITY_ID = "localityId"
    const val LAT = "lat"
    const val LON = "lon"
    const val INSTITUTION_ID = "institutionId"
    const val INSTITUTION_PROFILE_ID = "institutionProfileId"
    const val INSTITUTION_SIMILAR_NAME = "institutionSimilarName"
    const val FIRESTORE_REF = "userFirestoreRef"
    const val START_ELEMENT = "startElement"
    const val TAG = "tag"
    const val CATEGORY_ID = "categoryId"
    const val OFFER_ID = "offerId"
    const val DAY = "day"
    const val INSTANCE_ID = "instanceId"
    const val BIRTHDAY = "birthday"
    const val FCM_TOKEN = "fcmToken"
    const val EVENT_ID = "eventId"
    const val OFFER_TYPE = "offerType"
    const val RECOMMENDED = "recommended"
    const val AVATAR_URL = "avatarUrl"
    const val NAME = "name"
    const val GENDER = "gender"
    const val DATE_OF_BIRTH = "dateOfBirth"
    const val PUSH_AVAILABLE = "pushAvailable"
    const val YEAR = "year"
    const val MONTH = "month"
    const val STORY_ID = "storyId"
    const val SELECTION_NAME = "selectionName"
    const val SELECTION_ID = "selectionId"
    const val SELECTION_OFFER_ID = "selectionOfferId"
    const val STORY_TYPE = "storyType"
    const val LAST_FETCH_DAY = "lastFetchDate"
    const val BIRTHDAY_CAMPAIGN_USER_ID= "birthdayCampaignUserId"
    const val INSTRUCTION_ID = "instructionId"
    const val MARKETING_ID = "marketingId"
}